Logging to /tmp/openai-2018-10-18-10-55-28-077961
Logging to /tmp/openai-2018-10-18-10-55-29-292982
WARNING:tensorflow:From /cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
env_type: atari
Process Process-19:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-15:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-2:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-6:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-17:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-9:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-14:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-22:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-3:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-12:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-1:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-21:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-18:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-10:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-23:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-13:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-11:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-8:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-5:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-16:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-4:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-7:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-20:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Process Process-24:
Traceback (most recent call last):
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 7, in worker
    env = env_fn_wrapper.x()
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 30, in _thunk
    env = make_atari(env_id) if env_type == 'atari' else gym.make(env_id)
  File "/home/kclary/variability-RL/baselines/baselines/common/atari_wrappers.py", line 217, in make_atari
    env = gym.make(env_id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "/home/kclary/.local/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 9, in <module>
    import atari_py
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "/home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_python_interface.py", line 14, in <module>
    'ale_interface/build/libale_c.so'))
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/kclary/.local/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so)
Traceback (most recent call last):
  File "baselines/baselines/run.py", line 239, in <module>
    main()
  File "baselines/baselines/run.py", line 213, in main
    model, env = train(args, extra_args)
  File "baselines/baselines/run.py", line 65, in train
    env = build_env(args)
  File "baselines/baselines/run.py", line 97, in build_env
    env = make_vec_env(env_id, env_type, nenv, seed)
  File "/home/kclary/variability-RL/baselines/baselines/common/cmd_util.py", line 41, in make_vec_env
    if num_env > 1: return SubprocVecEnv([make_env(i + start_index) for i in range(num_env)])
  File "/home/kclary/variability-RL/baselines/baselines/common/vec_env/subproc_vec_env.py", line 58, in __init__
    observation_space, action_space = self.remotes[0].recv()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/cm/shared/apps/python/3.6.5-1804/lib/python3.6/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
